### ISSUE TITLE
【BE】環境構築

### ISSUE THREAD

**Issue by TAKO-zhangyu** [qin-team-recipe/01-backend#2]
BE -> Backend, バックエンドです。

バックエンドメンバーが開発を始められるよう、環境構築をすることがゴールです！

バックエンドメンバー:

- [@だるたに](https://qinsalon.slack.com/team/U058BG2S5G8)
- [@山本和樹](https://qinsalon.slack.com/team/U0570T19FDY)
- [@オタ](https://qinsalon.slack.com/team/U04GU7NV9D1)
- [@otono](https://qinsalon.slack.com/team/U054Q1E7ZMJ)

**Comment by TAKO-zhangyu** [comment]
1. このリポジトリをクローンする
2. Dockerをインストールする
  ・既にDockerを入れている方は不要です
  ・Windowsか、Mac（intel or M1, M2）でインストールするものが変わります
3. Dockerを起動したら、案内が出てくるので、その通りにDockerの設定をする
4. READMEに沿って対応する
   ・Windowsの方はdocker-compose.ymlを変更する必要があるので、オタにご連絡ください。

**Comment by toono-f** [comment]
@TAKO-zhangyu 
無事完了です!!
準備ありがとうございます🌟
