### ISSUE TITLE
仕様変更に伴うDBの修正

### ISSUE THREAD

**Issue by darutani** [qin-team-recipe/01-backend#56]
### 実装するテーブル

- [x] userとchefは統合
- [x] external_linkをuserとrecipeで分ける
- [x] user
  - [x] desciptionカラムを追加
  - [x] domainカラムを追加（半角小文字英数のランダム値）
  - [x] roleカラムを追加
  - [x] thumnailカラムを追加
  - [x] sns_idカラムを追加
- [x] recipe
  - [x] is_publicカラムを追加
  - [x] author_idはuser_idへ変更
  - [x] author_typeカラムを削除
- [x] material
  - [x] memoカラムを削除
  - [x] positionカラムを追加
- [x] step
  - [x] memoカラムを削除
  - [x] positionカラムを追加
  - [x] titleカラムをdescriptionカラムへ名称変更
  - [x] descriptionカラムの方をstringからtextへ変更
- [x] CartList
  - [x] own_notesカラムを追加
- [x] CartItem
  - [x] memoカラムを削除
  - [x] positionカラムを追加
- [x] FavoriteChef
  - [x] テーブル名をRelationshipsに変更
  - [x] user_idをfollowed_idにカラム名を変更
  - [x] chef_idをfollower_idにカラム名を変更

### 修正するリレーション

- [ ] FavoriteChef
  - [ ] Relationshipに変更
  - [ ] follower,followedそれぞれがUserと一対多のリレーションになるよう修正
- [ ] User
  - [ ] active_relationshipsのリレーションを定義
  - [ ] followingのリレーションを定義
  - [ ] passive_relationshipsのリレーションを定義
  - [ ] followersのリレーションを定義
- [ ] Recipe
  - [ ] authorのリレーションを削除
  - [ ] recipe_external_linksのリレーションを追加
  - [ ] belongs_to :userを追加
  - [ ] 中間テーブルfavorite_recipesを通したuserとのリレーションの記述方法を修正。（上記belongs_to :userと重複するため）
- [ ] chef
  - [ ] ファイル毎削除
- [ ] external_link
  - [ ] ファイル毎削除

### DB設計
https://www.notion.so/DB-a861ffd705a4414298c001e3c7bb1054

**Comment by TAKO-zhangyu** [comment]
以下チケットはここに統合
https://github.com/orgs/qin-team-recipe/projects/2/views/1?pane=issue&itemId=32386203
