### ISSUE TITLE
BEリポジトリをfly.ioにデプロイ

### ISSUE THREAD

**Issue by TAKO-zhangyu** [qin-team-recipe/01-backend#9]

**Comment by shanbenkazuki** [comment]
さくっとできると思っていたのだけど、よくわからないエラーが出てしまったので、後回しにしようかな
https://www.notion.so/fly-io-e93ddf42666842f8bad58d65d7f8e1c0?pvs=4


あるいはもしできそうな方いれば、やっていただければと
